// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// TERMINOLOGY CONSTANTS — Single Source of Truth
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
import type { SeverityTier, LeanCategory } from '@/types';

// ── Divergence Thresholds ────────────────────────────
export const DIVERGENCE_THRESHOLDS = {
    LOW_MAX: 29,
    MODERATE_MAX: 59,
    HIGH_MAX: 79,
    // 80–100 = Extreme
} as const;

export const FRACTURED_THRESHOLD = 40;
export const FRACTURED_MIN_SOURCES = 2;

// ── Lean Thresholds ──────────────────────────────────
export const LEAN_THRESHOLDS = {
    FAR_LEFT_MAX: -0.6,
    LEFT_MAX: -0.2,
    CENTER_MAX: 0.2,
    RIGHT_MAX: 0.6,
} as const;

// ── Severity Functions ───────────────────────────────
export function severityTier(score: number | null): SeverityTier {
    if (score === null || score === undefined) return 'Low';
    if (score <= DIVERGENCE_THRESHOLDS.LOW_MAX) return 'Low';
    if (score <= DIVERGENCE_THRESHOLDS.MODERATE_MAX) return 'Moderate';
    if (score <= DIVERGENCE_THRESHOLDS.HIGH_MAX) return 'High';
    return 'Extreme';
}

export function severityColor(tier: SeverityTier): string {
    switch (tier) {
        case 'Low': return 'var(--color-diverge-low)';
        case 'Moderate': return 'var(--color-diverge-mod)';
        case 'High': return 'var(--color-diverge-high)';
        case 'Extreme': return 'var(--color-diverge-ext)';
    }
}

export function severityBg(tier: SeverityTier): string {
    switch (tier) {
        case 'Low': return 'var(--color-diverge-low-bg)';
        case 'Moderate': return 'var(--color-diverge-mod-bg)';
        case 'High': return 'var(--color-diverge-high-bg)';
        case 'Extreme': return 'var(--color-diverge-ext-bg)';
    }
}

// ── Lean Functions ───────────────────────────────────
export function leanCategory(score: number | null): LeanCategory {
    if (score === null || score === undefined) return 'Center';
    if (score <= LEAN_THRESHOLDS.FAR_LEFT_MAX) return 'Far Left';
    if (score <= LEAN_THRESHOLDS.LEFT_MAX) return 'Left-Leaning';
    if (score <= LEAN_THRESHOLDS.CENTER_MAX) return 'Center';
    if (score <= LEAN_THRESHOLDS.RIGHT_MAX) return 'Right-Leaning';
    return 'Far Right';
}

export function leanColor(score: number | null): string {
    if (score === null) return 'var(--color-lean-center)';
    if (score < -0.15) return 'var(--color-lean-left)';
    if (score > 0.15) return 'var(--color-lean-right)';
    return 'var(--color-lean-center)';
}

export const divDotClass = (score: number): string => {
    if (score >= 80) return 'ns-div-dot ns-div-dot-extreme';
    if (score >= 60) return 'ns-div-dot ns-div-dot-high';
    if (score >= 30) return 'ns-div-dot ns-div-dot-moderate';
    return 'ns-div-dot ns-div-dot-low';
};

export const divTextClass = (score: number): string => {
    if (score >= 80) return 'ns-div-text-extreme';
    if (score >= 60) return 'ns-div-text-high';
    if (score >= 30) return 'ns-div-text-moderate';
    return 'ns-div-text-low';
};

export const leanDotClass = (lean: number): string => {
    if (lean < -0.15) return 'ns-div-dot ns-lean-dot-left';
    if (lean > 0.15) return 'ns-div-dot ns-lean-dot-right';
    return 'ns-div-dot ns-lean-dot-center';
};

export const leanTextClass = (lean: number): string => {
    if (lean < -0.15) return 'ns-lean-left';
    if (lean > 0.15) return 'ns-lean-right';
    return 'ns-lean-center';
};

// ── Labels ───────────────────────────────────────────
export const LABELS = {
    APP_NAME: 'Fracture',
    APP_TAGLINE: 'See the full story. Every side. Every frame.',
    FDI_NAME: 'Fracture Divergence Index',
    FDI_SHORT: 'FDI',
    BRIEF_TITLE: 'Fracture Brief',
    BRIEF_SUBTITLE: 'AI-generated synthesis of coverage',
    BRIEF_DISCLAIMER: 'Generated by AI based on coverage data across multiple outlets.',

    SCORE_LABELS: {
        headlineSentimentSpread: 'Headline Tone',
        framingTypeEntropy: 'Framing Approach',
        entityFramingDivergence: 'Entity Portrayal',
        linguisticEmbeddingSpread: 'Language Similarity',
        sourceSelectionVariance: 'Source Selection',
        structuralDivergence: 'Structural Difference',
    },

    SCORE_WEIGHTS: {
        headlineSentimentSpread: 0.25,
        framingTypeEntropy: 0.20,
        entityFramingDivergence: 0.20,
        linguisticEmbeddingSpread: 0.15,
        sourceSelectionVariance: 0.10,
        structuralDivergence: 0.10,
    },

    STATUS: {
        BREAKING: 'Breaking',
        ACTIVE: 'Active',
        ARCHIVED: 'Archived',
    },

    CATEGORIES: {
        politics: 'Politics',
        world: 'World',
        economy: 'Economy',
        conflict: 'Conflict',
        elections: 'Elections',
        policy: 'Policy',
        geopolitics: 'Geopolitics',
        uncategorized: 'News',
    } as Record<string, string>,

    NAV: {
        HOME: 'Home',
        STORIES: 'Stories',
        BRIEFING: 'Briefing',
        SEARCH: 'Search',
        PRICING: 'Pricing',
    },
} as const;

export function divergenceLabel(score: number | null): string {
    const tier = severityTier(score);
    if (score === null) return 'Not scored';
    return `${tier} (${Math.round(score)})`;
}

export function getDivergenceColor(score: number): string {
    if (score >= 80) return '#991B1B';
    if (score >= 60) return '#DC2626';
    if (score >= 30) return '#D97706';
    return '#16A34A';
}

export function categoryLabel(category: string): string {
    return LABELS.CATEGORIES[category] || category;
}
